<?php
/**
 * Language strings for local_epicereports (English)
 *
 * @package    local_epicereports
 * @copyright  2024 Your Name <your@email.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// General.
$string['pluginname'] = 'EpicE Reports';
$string['pluginname_help'] = 'Advanced reporting system for Moodle';

// Capabilities.
$string['epicereports:view'] = 'View EpicE reports';

// Dashboard.
$string['dashboard'] = 'Dashboard';
$string['active_users'] = 'Active Users';
$string['visible_courses'] = 'Visible Courses';
$string['hidden_courses'] = 'Hidden Courses';
$string['total_enrolments'] = 'Total Enrolments';
$string['satisfaction_percent'] = 'Satisfaction Percentage';

// Course listing.
$string['courses'] = 'Courses';
$string['courselist'] = 'Course List';
$string['allcategories'] = 'All categories';
$string['allstatus'] = 'All statuses';
$string['visiblecourses'] = 'Visible';
$string['hiddencourses'] = 'Hidden';
$string['filter'] = 'Filter';
$string['viewdetail'] = 'View detail';

// Course detail.
$string['coursedetail'] = 'Course Detail';
$string['generalinfo'] = 'General Information';
$string['shortname'] = 'Short name';
$string['visibility'] = 'Visibility';
$string['visible'] = 'Visible';
$string['hidden'] = 'Hidden';
$string['enrolledusers'] = 'Enrolled students and progress';

// Export.
$string['export'] = 'Export';
$string['exporttoexcel'] = 'Export to Excel';
$string['downloadexcel'] = 'Download Excel';
$string['preview'] = 'Data Preview for Export';
$string['previewdescription'] = 'Below is a preview of the data that will be exported. If everything looks correct, you can download the Excel file from the button above.';
$string['coursereport'] = 'Course Report';
$string['generatedby'] = 'Generated by EpicE Reports on';
$string['exportdate'] = 'Export date';

// User table.
$string['userid'] = 'User ID';
$string['username'] = 'Username';
$string['idnumber'] = 'ID Number';
$string['fullname'] = 'Full name';
$string['email'] = 'Email';
$string['firstaccess'] = 'First access';
$string['lastaccess'] = 'Last access';
$string['groups'] = 'Groups';

// Activity states.
$string['status'] = 'status';
$string['attempts'] = 'attempts';
$string['score'] = 'score';
$string['highestgrade'] = 'highest grade';
$string['submission'] = 'submission';
$string['submissiondate'] = 'submission date';
$string['grade'] = 'grade';

// Completion states.
$string['completed'] = 'Completed';
$string['inprogress'] = 'In progress';
$string['notstarted'] = 'Not started';
$string['pending'] = 'Pending';
$string['finished'] = 'Finished';

// Summary.
$string['summary'] = 'Summary';
$string['criteria'] = 'Criteria';
$string['count'] = 'Count';
$string['percentage'] = 'Percentage';
$string['enrolled'] = 'Enrolled';
$string['started'] = 'Started';
$string['certificated'] = 'Certificated';

// Final columns.
$string['certificate'] = 'Certificate';
$string['progress'] = 'Progress';
$string['finalgrade'] = 'Final Grade (%)';
$string['completiondate'] = 'Completion date';
$string['completionstatus'] = 'Completion status';
$string['userdata'] = 'User Data';

// Certificates.
$string['issued'] = 'Issued';
$string['notissued'] = 'Not issued';
$string['downloadcertificates'] = 'Download certificates';
$string['downloadcertificates_help'] = 'Download all issued certificates in this course as a ZIP file';
$string['nocertificates'] = 'There are no certificate activities in this course.';
$string['noissuedcertificates'] = 'There are no issued certificates in this course.';
$string['nofilesfound'] = 'No certificate PDF files found.';
$string['nofilesfound_help'] = 'The certificate PDF files could not be located. This may happen if certificates are generated dynamically or if files were deleted.';

// Feedback.
$string['exportfeedback'] = 'Export feedback';
$string['exportfeedback_help'] = 'Export all feedback responses from this course to Excel';
$string['feedbackreport'] = 'Feedback Report';
$string['nofeedback'] = 'There are no feedback activities in this course.';
$string['nofeedbackresponses'] = 'There are no feedback responses in this course.';
$string['responsesnumber'] = 'Response number';

// Submissions.
$string['submitted'] = 'Submitted';
$string['notsubmitted'] = 'Not submitted';

// Messages.
$string['nousers'] = 'There are no users enrolled in this course.';
$string['nocourses'] = 'No courses available.';
$string['invalidcourseid'] = 'Invalid course ID.';

// Navigation.
$string['back'] = 'Back';
$string['backtoplatform'] = 'Back to platform';

// Course.
$string['course'] = 'Course';
$string['courseid'] = 'Course ID';
$string['category'] = 'Category';

// Other.
$string['all'] = 'All';
$string['yes'] = 'Yes';
$string['no'] = 'No';
$string['actions'] = 'Actions';